defaults:
- data: cifar10
- peft: ft
training:
    metric_name: accuracy
    batch_size: 16
    epochs: 2
    learning_rate: 2e-4
    optimizer: adam
    scheduler: linear
model:
    model_name: google/vit-base-patch16-224-in21k
    